@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.uraneptus.sullysmod.client.particles;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;