@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.uraneptus.sullysmod.client.model.ancient_skulls;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;